## SPDX-License-Identifier: FSFAP
## Copyright (C) 2014-2019 Colin B. Macdonald
## Copyright (C) 2016-2017 Abhinav Tripathi
## Copyright (C) 2016 Marco Falke
## Copyright (C) 2016-2019 Mike Miller
##
## Copying and distribution of this file, with or without modification,
## are permitted in any medium without royalty provided the copyright
## notice and this notice are preserved.  This file is offered as-is,
## without any warranty.
##
## .travis.yml - Travis CI configuration for Octave's Symbolic package

dist: xenial
language: generic

services:
- docker

matrix:
  include:
  - env: PYVER=2 PYTHONIC=no  SYMPY=1.2   OCT=4.2   MPMATH=1.0 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=no  SYMPY=1.2   OCT=4.2   MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=no  SYMPY=1.3   OCT=4.4   MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=no  SYMPY=1.4   OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=no  SYMPY=1.5.1 OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=no  SYMPY=1.2   OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=no  SYMPY=1.3   OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=no  SYMPY=1.4   OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=no  SYMPY=1.5.1 OCT=4.2   MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=no  SYMPY=1.5.1 OCT=4.4   MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=no  SYMPY=1.5.1 OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=no  SYMPY=1.5.1 OCT=devel MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=yes SYMPY=1.5.1 OCT=4.4   MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=yes SYMPY=1.5.1 OCT=4.4   MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=yes SYMPY=1.5.1 OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=yes SYMPY=1.5.1 OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=yes SYMPY=1.5.1 OCT=devel MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=yes SYMPY=1.5.1 OCT=devel MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=dev SYMPY=1.5.1 OCT=devel MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=dev SYMPY=1.5.1 OCT=devel MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=dev SYMPY=1.5.1 OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=dev SYMPY=1.5.1 OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  allow_failures:
  - env: PYVER=3 PYTHONIC=no  SYMPY=1.5.1 OCT=devel MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=yes SYMPY=1.5.1 OCT=devel MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=yes SYMPY=1.5.1 OCT=devel MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=dev SYMPY=1.5.1 OCT=devel MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=dev SYMPY=1.5.1 OCT=devel MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=3 PYTHONIC=dev SYMPY=1.5.1 OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80
  - env: PYVER=2 PYTHONIC=dev SYMPY=1.5.1 OCT=5     MPMATH=1.1 DOCTEST=yes COLUMNS=80

before_install:
- docker pull mtmiller/octave:${OCT}
- docker run --name=oc --detach --init --env=LC_ALL=C.UTF-8 --env=PYTHON_VERSION=${PYVER} --env=PYTHON=python${PYVER} --volume=$PWD:/octsympy:z mtmiller/octave:${OCT} sleep inf

install:
- docker exec oc pip${PYVER} install mpmath==${MPMATH}
- docker exec oc pip${PYVER} install sympy==${SYMPY}
- if [ "x$DOCTEST" = "xyes" ]; then
      docker exec oc octave --eval "pkg install -forge doctest";
  fi
- if [ "x$PYTHONIC" = "xyes" ]; then
      docker exec oc octave --eval "pkg install https://octave-pythonic-downloads.s3.amazonaws.com/releases/octave-pythonic-0.0.1.tar.gz";
  fi
- if [ "x$PYTHONIC" = "xdev" ]; then
      docker exec oc octave --eval "pkg install https://gitlab.com/mtmiller/octave-pythonic/-/archive/master/octave-pythonic-master.tar.gz";
  fi
- if [ "x$PYTHONIC" != "xno" ]; then
      docker exec oc bash -c "echo 'pkg load pythonic' >> ~/.octaverc";
  fi

script:
- stty cols $COLUMNS rows 40
- tput cols; stty size
- docker exec oc make -C octsympy test;
- docker exec oc cat octsympy/fntests.log
- if [ "x$DOCTEST" = "xyes" ]; then
      docker exec oc make -C octsympy doctest;
  fi

after_script:
- docker stop oc
